# mandatory (#mandatory), optional (#optional).
# The overall format is standard TOML format, v0.5.0.
modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"
logoFile="ring_amethyst.png"
issueTrackerURL="https://github.com/BrassAmber-Mods/Brass_Geodes/issues"
[[mods]]
    modId="brass_geodes"
    version="${file.jarVersion}"
    displayName="BrassGeodes"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/brassgeodes"
    credits="BrassMcrafty for all textures, Milamber for code"
    authors="Milamber and BrassMcrafty"
    description='''
    A small mod that adds different gem geodes in all biomes instead of just amethyst geodes.
    '''

[[dependencies.brass_geodes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
